In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4], [6,7,8,9], [10,11,12,13], [14,15,16,17]])
print(a)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


In [4]:
a.nbytes

64

In [5]:
a[:, 1] = [1,2,3,4]
print(a)

[[ 1  1  3  4]
 [ 6  2  8  9]
 [10  3 12 13]
 [14  4 16 17]]


In [6]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
b[1, 1, 1]

8

In [8]:
np.ones((1,2,2))

array([[[1., 1.],
        [1., 1.]]])

In [9]:
np.full((3,3), 'deeznuts')

array([['deeznuts', 'deeznuts', 'deeznuts'],
       ['deeznuts', 'deeznuts', 'deeznuts'],
       ['deeznuts', 'deeznuts', 'deeznuts']], dtype='<U8')

In [10]:
np.random.randint(0, 100, size=(3,3))

array([[17, 43, 48],
       [ 7, 62, 30],
       [ 1, 61, 63]])

In [11]:
a = np.ones((5,5))
a[1:-1, 1:-1] = 0
a[2,2] = 9
print(a)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
a = np.ones((5,5))
b = np.zeros((3,3))
b[1,1] = 9

a[1:-1, 1:-1] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# Do this if we want to create a duplicate and then edit on the DUPLICATE AND NOT THE ORIGINAL
d = a.copy()
d[2,2]=10
print(a,)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
c = a[:, np.newaxis]
print(c)

[[[1. 1. 1. 1. 1.]]

 [[1. 0. 0. 0. 1.]]

 [[1. 0. 9. 0. 1.]]

 [[1. 0. 0. 0. 1.]]

 [[1. 1. 1. 1. 1.]]]


In [15]:
test1 = np.random.randint(0, 10, size = (3,2))
test2 = np.random.randint(0, 10, size = (2,3))
final = np.dot(test2, test1)
print(final)
np.linalg.inv(final)


[[47 46]
 [51 62]]


array([[ 0.10915493, -0.08098592],
       [-0.08978873,  0.08274648]])

In [16]:
#Loading data from file
filedata = np.genfromtxt('New Text Document.txt', delimiter=',')
filedata.astype('int32')

array([[     1,      2,      3,      4,      5,      6,      7,      8,
             9,   1123,  12345],
       [   123,      1,     32,     54,     76,     43,     45,    654,
             6,     65,      6],
       [    34,    423,    423, 234324,    432,    342, 432432,    657,
            12,     19,   1234]])

In [17]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
a[[[1,2]], [[0,2]]]

array([[1., 9.]])

In [36]:
x = np.arange(1, 31).reshape(6,5)
print(x)
x[[0,1,2,3],[1,2,3,4]]
x[2:4, 0:2]
x[[0,4,5], 3:]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
@@@Note that when indexing, array[rows, columns]

In [ ]:
###END